"""empty message

Revision ID: bfa596e34610
Revises: d39440876cff
Create Date: 2019-11-26 14:53:20.182367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfa596e34610'
down_revision = 'd39440876cff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('time', sa.Integer(), nullable=False))
    op.drop_column('scores', 'score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('scores', 'time')
    # ### end Alembic commands ###
