"""empty message

Revision ID: d39440876cff
Revises: 
Create Date: 2019-11-26 14:49:32.364734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd39440876cff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('errors', sa.Integer(), nullable=False))
    op.add_column('scores', sa.Column('wpm', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scores', 'wpm')
    op.drop_column('scores', 'errors')
    # ### end Alembic commands ###
